---
k3s_version: v1.26.1+k3s1
ansible_user: rocky
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: " --advertise-address {{ master_ip }} --tls-san {{ master_ip }}"
extra_agent_args: ""
